service: auth-service

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    REGION: ${self:provider.region}

# Add layers configuration
layers:
  CommonLayer:
    path: layers

# Add package configuration
package:
  individually: true
  exclude:
    - layers/nodejs/node_modules/**

functions:
  - ${file(resources/lambda.yml)}

resources:
  - ${file(resources/cognito.yml)}
  - ${file(resources/iam_role.yml)}
  - Resources:
      ApiAuthorizer:
        Type: AWS::ApiGateway::Authorizer
        Properties:
          Name: CognitoAuthorizer
          Type: COGNITO_USER_POOLS
          IdentitySource: method.request.header.Authorization
          RestApiId: !Ref ApiGatewayRestApi
          ProviderARNs:
            - !GetAtt CognitoUserPool.Arn

      ApiGatewayRestApi:
        Type: AWS::ApiGateway::RestApi
        Properties:
          Name: ${self:service}-api-${self:provider.stage}
          # Enable CORS for all methods
          EndpointConfiguration:
            Types:
              - REGIONAL

      # Add global CORS configuration
      GatewayResponseDefault4XX:
        Type: 'AWS::ApiGateway::GatewayResponse'
        Properties:
          ResponseParameters:
            gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
            gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent'"
            gatewayresponse.header.Access-Control-Allow-Methods: "'OPTIONS,GET,PUT,POST,DELETE,PATCH'"
          ResponseType: DEFAULT_4XX
          RestApiId: !Ref ApiGatewayRestApi

      GatewayResponseDefault5XX:
        Type: 'AWS::ApiGateway::GatewayResponse'
        Properties:
          ResponseParameters:
            gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
            gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent'"
            gatewayresponse.header.Access-Control-Allow-Methods: "'OPTIONS,GET,PUT,POST,DELETE,PATCH'"
          ResponseType: DEFAULT_5XX
          RestApiId: !Ref ApiGatewayRestApi
          
  - Outputs:
      UserPoolId:
        Value: !Ref CognitoUserPool
        Export:
          Name: ${self:service}-UserPoolId-${self:provider.stage}
      UserPoolClientId:
        Value: !Ref CognitoUserPoolClient
        Export:
          Name: ${self:service}-UserPoolClientId-${self:provider.stage}
      ApiUrl:
        Value: !Sub "https://${ApiGatewayRestApi}.execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}"
        Export:
          Name: ${self:service}-ApiUrl-${self:provider.stage}
      IdentityPoolId:
        Value: !Ref CognitoIdentityPool
        Export:
          Name: ${self:service}-IdentityPoolId-${self:provider.stage}