Resources:
  CognitoSmsPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "CognitoSmsPolicy"
      Roles:
        - !Ref CognitoSmsRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "sns:Publish"
            Resource: "*"