name: Deploy to AWS

on:
  push:
    branches:
      - dev
      - test
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Serverless Framework
        run: npm install -g serverless
        
      - name: Install dependencies
        run: npm install
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets[format('AWS_ACCESS_KEY_ID_{0}', github.ref_name == 'dev' ? 'DEV' : github.ref_name == 'test' ? 'TEST' : 'PROD')] }}
          aws-secret-access-key: ${{ secrets[format('AWS_SECRET_ACCESS_KEY_{0}', github.ref_name == 'dev' ? 'DEV' : github.ref_name == 'test' ? 'TEST' : 'PROD')] }}
          aws-region: ${{ github.ref_name == 'prod' && 'us-west-1' || 'us-east-2' }}
          
      - name: Deploy to AWS
        run: |
          STAGE=${{ github.ref_name }}
          sls deploy --stage $STAGE \
            --param COGNITO_USER_POOL_ID=${{ secrets[format('COGNITO_USER_POOL_ID_{0}', github.ref_name == 'dev' ? 'DEV' : github.ref_name == 'test' ? 'TEST' : 'PROD')] }} \
            --param COGNITO_CLIENT_ID=${{ secrets[format('COGNITO_CLIENT_ID_{0}', github.ref_name == 'dev' ? 'DEV' : github.ref_name == 'test' ? 'TEST' : 'PROD')] }}