name: Deploy Backend with CloudFormation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Change to your preferred region
        
    - name: Deploy CloudFormation stack
      run: |
        # Upload CloudFormation template to S3
        TIMESTAMP=$(date +%s)
        aws s3 mb s3://backend-deployment-$TIMESTAMP --region us-east-1 || true
        aws s3 cp cloudformation.yml s3://backend-deployment-$TIMESTAMP/
        
        # Deploy stack
        STACK_NAME="backend-stack-$TIMESTAMP"
        aws cloudformation create-stack \
          --stack-name $STACK_NAME \
          --template-url https://backend-deployment-$TIMESTAMP.s3.amazonaws.com/cloudformation.yml \
          --parameters \
            ParameterKey=GitHubRepo,ParameterValue=https://github.com/${{ github.repository }}.git \
          --capabilities CAPABILITY_IAM
        
        echo "Waiting for stack creation to complete..."
        aws cloudformation wait stack-create-complete --stack-name $STACK_NAME
        
        # Get outputs
        PUBLIC_IP=$(aws cloudformation describe-stacks \
          --stack-name $STACK_NAME \
          --query "Stacks[0].Outputs[?OutputKey=='PublicIP'].OutputValue" \
          --output text)
          
        echo "Backend server deployed with IP: $PUBLIC_IP"
        echo "INSTANCE_IP=$PUBLIC_IP" >> $GITHUB_OUTPUT